TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 0.45
  acc_lim_y: 0.0

  holonomic_robot: false

#TrajectoryPlannerROS:
#
#  holonomic_robot: false
#  sim_time: 1.0
#  meter_scoring: false
#  pdist_scale: 0.6
#  yaw_goal_tolerance: 0.05
#  xy_goal_tolerance: 0.05
#  controller_frequency: 1
#  acc_lim_x: 4.5
#  acc_lim_y: 2.5
#  acc_lim_theta: 3.2
#  max_vel_x: 4.5
#  min_vel_x: 0.1
#  max_vel_theta: 1.0
#  min_vel_theta: -1.0
#  min_in_place_vel_theta: 0.4

