map_type: costmap

obstacle_range: 5.0
raytrace_range: 4.90
#footprint: [[0.2, 0.1], [0.2, -0.1], [-0.2, -0.1], [-0.2, 0.1]]
transform_tolerance: 0.2


robot_radius: 0.20 
# Maximum distance the obstacle will have from the centre if the robot
inflation_radius: 0.90

# Controls the visualization on Rviz
publish_frequency: 50
# Controls the quickly sensor data makes it into the costmap
map_update_rate: 50

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
