local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   publish_frequency: 10.0
   width: 5.0
   height: 5.0
   resolution: 0.05
# false because the LOCAL static map keeps changing 
   static_map: false
# Map remains centered around the robot if true
   rolling_window: true
